# Generated by Django 3.2.6 on 2022-05-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_tital', models.CharField(max_length=100)),
                ('blog_description', models.TextField()),
                ('date_of_bloag_post', models.DateField()),
            ],
        ),
    ]
